profile=high-quality
save-position-on-quit
slang=eng,pl
alang=jpn,eng,pl

script-opts=chapterskip-skip=opening;ending;intro;credits

glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"

sub-pos=70
sub-scale=0.5
#needed for preview
osc=no
screenshot-directory="/home/kacper/Pictures/"
