profile=high-quality
save-position-on-quit
slang=eng,pl
alang=jpn,eng,pl
screenshot-directory="~/Pictures/mpv/"

script-opts=chapterskip-skip=opening;ending;intro;credits

sub-pos=70
sub-scale=0.5
#needed for preview
osc=no
